# Generated by Django 4.0.6 on 2022-07-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('CID', models.BigAutoField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('fname', models.CharField(max_length=50)),
                ('midname', models.CharField(blank=True, max_length=50, null=True)),
                ('lname', models.CharField(blank=True, max_length=50, null=True)),
                ('Phone', models.BigIntegerField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('Course', models.CharField(max_length=100)),
            ],
        ),
    ]
