# Generated by Django 4.0.6 on 2022-07-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_id', models.CharField(default='0', max_length=10)),
                ('certificate_id', models.CharField(max_length=10)),
                ('fname', models.CharField(max_length=50)),
                ('midname', models.CharField(blank=True, max_length=50, null=True)),
                ('lname', models.CharField(blank=True, max_length=50, null=True)),
                ('Phone', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Course', models.CharField(max_length=100)),
            ],
        ),
    ]
