# Generated by Django 4.0.6 on 2022-07-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_handler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='CID',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='certificates',
            name='Phone',
            field=models.IntegerField(max_length=10),
        ),
    ]
