# Generated by Django 4.0.6 on 2022-07-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_handler', '0002_alter_certificates_cid_alter_certificates_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='Phone',
            field=models.IntegerField(),
        ),
    ]
