# Generated by Django 4.0.6 on 2022-07-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons1',
            name='discount',
            field=models.IntegerField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='coupons1',
            name='valid_for',
            field=models.IntegerField(default='', max_length=100),
        ),
    ]
