# Generated by Django 3.2.7 on 2022-07-10 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coupons',
            new_name='Coupons1',
        ),
    ]
