# Generated by Django 4.0.6 on 2022-07-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_alter_coupons1_discount_alter_coupons1_valid_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons1',
            name='discount',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='coupons1',
            name='valid_for',
            field=models.IntegerField(default=''),
        ),
    ]
