# Generated by Django 3.2.7 on 2022-07-10 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_rename_coupons_coupons1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupons1',
            old_name='coupons',
            new_name='coupons2',
        ),
    ]
