# Generated by Django 3.2.7 on 2022-07-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupons', models.CharField(default='', max_length=70)),
                ('discount', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
